environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g gulp-cli
  - npm i

cache:
  - node_modules
  - '%APPDATA%\npm-cache'

test_script:
  - node --version
  - npm --version
  - gulp
  - gulp test

build: off
